-- Conectar al PDB (Pluggable Database)
ALTER SESSION SET CONTAINER = XEPDB1;

-- Conectar como usuario de la aplicación (ya creado automáticamente)
ALTER SESSION SET CURRENT_SCHEMA = AGENDA;

 CREATE TABLE persona (
    id_persona NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre      VARCHAR2(100) NOT NULL,
    apellido    VARCHAR2(200) NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (id_persona)
);

CREATE TABLE Usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona NUMBER UNIQUE,
    email VARCHAR2(150) UNIQUE,
    password VARCHAR2(256),
    CONSTRAINT fk_persona_usuario FOREIGN KEY (id_persona) REFERENCES persona(id_persona)
);

CREATE TABLE estatus_actividad (
    codigo_estatus VARCHAR2(3) PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL 
);

CREATE TABLE actividades(
	id_actividad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nombre varchar(200) NOT NULL,
	fecha DATE,
	hora_inicio DATE,
	hora_fin DATE,
	comentario varchar(200),
    cod_estatus VARCHAR2(3),
    id_persona NUMBER,
    CONSTRAINT fk_actividad_estatus FOREIGN KEY (cod_estatus) 
    REFERENCES estatus_actividad(codigo_estatus),
    CONSTRAINT fk_actividad_persona FOREIGN KEY (id_persona)
    REFERENCES persona(id_persona)
);

INSERT INTO estatus_actividad (codigo_estatus, descripcion) 
VALUES ('INI', 'INICIADO');

INSERT INTO estatus_actividad (codigo_estatus, descripcion) 
VALUES ('PEN', 'PENDIENTE');

INSERT INTO estatus_actividad (codigo_estatus, descripcion) 
VALUES ('FIN', 'FINALIZADO');
COMMIT;

BEGIN
    DBMS_OUTPUT.PUT_LINE('✅ Base de datos inicializada correctamente');
END;
/